import { getBackendUrl } from "~/config";
import { getAccessToken } from "./auth";

// An empty BACKEND_URL is the *expected* local-dev default (research.md §8 —
// same-origin, matching vite.config.ts's /api proxy), so only warn when
// window.__ENV__ was actually generated by the Docker entrypoint (i.e. the
// key is present) and came through empty — that's a real missing-value case
// (FR-008/User Story 3), unlike dev's placeholder config.js which never sets
// the key at all.
if (window.__ENV__ && "BACKEND_URL" in window.__ENV__ && !window.__ENV__.BACKEND_URL) {
  console.warn("FRONTEND_BACKEND_URL is not set — API requests will fail unless the frontend happens to share an origin with the backend.");
}

export class ApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

async function request<TResponse>(path: string, init?: RequestInit): Promise<TResponse> {
  const token = await getAccessToken();
  const response = await fetch(`${getBackendUrl()}/api${path}`, {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...init?.headers,
    },
  });

  if (!response.ok) {
    const body = await response.text();
    throw new ApiError(response.status, body || response.statusText);
  }
  if (response.status === 204) {
    return undefined as TResponse;
  }
  return (await response.json()) as TResponse;
}

export const api = {
  get: <T>(path: string) => request<T>(path, { method: "GET" }),
  post: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: "POST", body: body ? JSON.stringify(body) : undefined }),
  put: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: "PUT", body: body ? JSON.stringify(body) : undefined }),
  delete: <T>(path: string) => request<T>(path, { method: "DELETE" }),
};
